#!bin/bash
#==================================================
# Script Name	:       disp_prod_by_cat
# By		:       Xymond Louisse M. Alcazar
# Group Name	:       Team Lemar
# Purpose	:       a script that displays
#                       products by its category.
# Command Line	:       disp_prod_by_cat
#==================================================
products=./res/IPSdataset.txt

# script for center_text
source ./res/my_funcs

category() {
	local pid="$1"
	increment=7
	pid_match=$(grep -i "^$pid" "$products")

	clear
	if [[ -z "$pid" ]]
	then
		echo -e "\n\n\n\n\n"
		center_text "No Entry, Please Enter the corresponding letter of the category."
		echo -e "\n\n\n"
		center_text "Press [ENTER] to continue"
		read
	elif [[ -z "$pid_match" ]]
	then
		echo -e "\n\n\n\n\n"
		center_text "No matching products."
		echo -e "\n\n\n"
		center_text "Press [ENTER] to continue"
		read
	else
		tput cup 5 10;printf "%-10s %-35s %-20s %-20s %10s %10s %10s %15s\n" "PID" "Product" "Category" "Supplier" "Price" "Quantity" "Sales" "Threshold"
		tput cup 6 10;echo -e "========================================================================================================================================="

		echo "$pid_match" | while IFS=':' read -r PID pName pCategory pSupplier price count sales pThreshold
		do
			tput cup "$increment" 10;printf "%-10s %-35s %-20s %-20s %10s %10s %10s %15s\n" "$PID" "$pName" "$pCategory" "$pSupplier" "$price" "$count" "$sales" "$pThreshold"

			((increment++))
		done
		echo -e "\n\n"
		center_text "Press [ENTER] to return"
		read;clear;continue
	fi
}

while true
do
	clear
        echo -e "\n\n\n\n\n"
	center_text "Display Products by Category"
	center_text "============================"
        echo ""
	center_text "[CC] - Chips & Crackers	[BB] - Bread & Bakery"
        center_text "[CN] - Condiments		[IN] - Instant Noodles"
        center_text "[PN] - Pasta& Noodless		[BC] - Biscuits & Cookies"
        center_text "[DE] - Dairy & Eggs		[CG] - Canned Goods"
        center_text "[FD] - Frozen Desserts		[FM] - Frozen Meat"
	center_text "[BV] - Beverages		[PS] - Pet Supplies"
	echo ""
	center_text "(Press [Q] to exit)"
        echo ""
	read -p "$(center_text 'Enter Code: ')" choice

	if [[ "$choice" =~ ^[Qq]$ ]]
	then
		clear;exit
	else
		category "$choice"
	fi
done
