#!bin/bash
#=================================================
# Script Name	:	disp_all_prod
# By		:	Xymond Louisse M. Alcazar
# Group		:	Group Lemar
# Purpose	:	displays all products read
#			from the file.
#=================================================

#file name & path
products=./res/IPSdataset.txt

#function for center text
source ./res/my_funcs

#to set the tput cup horizontal positions of the contents.
increment=7

clear
tput cup 5 10;printf "%-10s %-35s %-20s %-20s %10s %10s %10s %15s\n" "PID" "Product" "Category" "Supplier" "Price" "Quantity" "Sales" "Threshold"
tput cup 6 10;echo -e "========================================================================================================================================="

while IFS=':' read -r PID pName pCategory pSupplier price count sales pThreshold
do
	tput cup "$increment" 10;printf "%-10s %-35s %-20s %-20s %10s %10s %10s %15s\n" "$PID" "$pName" "$pCategory" "$pSupplier" "$price" "$count" "$sales" "$pThreshold"
	((increment++))
done < "$products"
echo ""
center_text "Press [ENTER] to continue"
read
clear;exit
