#!bin/bash
#==================================================
# Script Name	:       prod_quant_per_cat
# By		:       Xymond Louisse M. Alcazar
# Group Name	:       Team Lemar
# Purpose	:       a script that displays
#			product quantity per
#			each category.
#==================================================
products=./res/IPSdataset.txt

# script for center_text
source ./res/my_funcs

#store data fields in a variable for easy access
IFS=':' read -r PID pName pCategory pSupplier price count <<< "$products"

clear
echo -e "\n\n\n\n\n"
center_text "Product Count per Category"
center_text "=========================="
echo ""
center_text "[CODE]   Category				Count"
center_text "------------------------------------------------"
center_text "[CC]     Chips & Crackers			$(grep -c 'CC' $PID)"
center_text "[CN]     Condiments			$(grep -c 'CN' $PID)"
center_text "[PN]     Pasta & Noodless			$(grep -c 'PN' $PID)"
center_text "[DE]     Dairy & Eggs			$(grep -c 'DE' $PID)"
center_text "[FD]     Frozen Desserts			$(grep -c 'FD' $PID)"
center_text "[BV]     Beverages				$(grep -c 'BV' $PID)"
center_text "[BB]     Bread & Bakery			$(grep -c 'BB' $PID)"
center_text "[IN]     Instant Noodles			$(grep -c 'IN' $PID)"
center_text "[BC]     Biscuits & Cookies		$(grep -c 'BC' $PID)"
center_text "[CG]     Canned Goods			$(grep -c 'CG' $PID)"
center_text "[FM]     Frozen Meat			$(grep -c 'FM' $PID)"
center_text "[PS]     Pet Supplies			$(grep -c 'PS' $PID)"
echo ""
center_text "Press [ENTER] to go back to menu"
read
clear;exit
