#!bin/bash
#==================================================
# Script Name:          prod_quant_per_stat
# By:                   Xymond Louisse M. Alcazar
# Group Name:           Team Lemar
# Purpose:              a script that displays
#                       product quantity by its
#                     	product status.
#Command Line:          prod_quant_per_stat
#==================================================
products=~/res/IPSdataset.txt
