#!bin/bash
#==================================================
# Script Name:          top_selling_products
# By:                   Xymond Louisse M. Alcazar
# Group Name:           Team Lemar
# Purpose:              a script that displays
#                       top selling products based
#			on sales.
#==================================================
products=~/res/IPSdataset.txt

IFS=':' read -r PID pName pCategory pSupplier price count sales <<< "$products"


