#!bin/bash
#==================================================
# Script Name:          avg_prod_quant_per_cat
# By:                   Xymond Louisse M. Alcazar
# Group Name:           Team Lemar
# Purpose:              a script that displays
#                       average product quantity
#                       per each category.
#Command Line:          avg_prod_quant_per_cat
#==================================================
products=~/res/IPSdataset.txt
